# -*- coding: utf-8 -*-
"""Mini-tests del Tema 5.1 (fuente única para el libro y la versión en línea)."""
from common import *

TESTS = {
 "listening": {"skill": "listening", "total": 6,
  "tip": ["Antes de escuchar, **lee todas las preguntas**. Así sabes qué información buscar.",
          "Pon atención a las palabras **than** (que) y **the most / the -est** (el más): ahí está casi siempre la respuesta."],
  "review": "Vocabulario (audio 01) y la práctica con el audio 04 en velocidad lenta",
  "parts": [{"intro": "Escucha a Luis, un guía turístico, presentando su pueblo. Puedes escuchar **dos veces como máximo**, como en una prueba real.",
             "audio": "05", "qs": [
    {"t": "mc", "q": "What is the name of Luis's town?", "opts": ["Los Santos", "Las Tablas", "Panama City"], "a": 1,
     "exp": "Luis dice *Welcome to my town, Las Tablas!* Los Santos es la **provincia** (*the most famous town in Los Santos*)."},
    {"t": "mc", "q": "Which is the busiest place in town?", "opts": ["the plaza", "the beach", "the library"], "a": 0,
     "exp": "*The plaza is the busiest place in town, because there are shops and restaurants around it.*"},
    {"t": "mc", "q": "Which is the oldest building?", "opts": ["the town hall", "the library", "the church"], "a": 2,
     "exp": "*The church is the oldest building. It is older than the town hall.*"},
    {"t": "tf", "q": "The library is the newest building.", "a": True, "exp": "*The library is the newest building. It opened last year.*"},
    {"t": "tf", "q": "The beach is busier than the plaza.", "a": False,
     "exp": "Es al revés: *it is **quieter** than the plaza*. La playa es más **tranquila**."},
    {"t": "mc", "q": "Why is Las Tablas famous?", "opts": ["because of the beach", "because of the Carnival", "because of the library"], "a": 1,
     "exp": "*Las Tablas is the most famous town in Los Santos because of the Carnival.*"},
  ]}]},

 "reading": {"skill": "reading", "total": 6,
  "tip": ["Lee primero las preguntas y luego el texto. **Subraya** en el texto la parte donde está cada respuesta.",
          "En las comparaciones, fíjate **qué lugar va primero**: *A is bigger than B* no es lo mismo que *B is bigger than A*."],
  "review": "La lectura *Sofía's Community* y la Gramática A y B",
  "parts": [{"intro": "Lee lo que Ana escribió sobre los dos lugares donde ha vivido y responde.",
             "reading": {"title": "Two Places I Love", "paras": [
                "Hi! I'm Ana. I live in Panama City, but my grandparents live in El Valle de Antón. I love both places!",
                "Panama City is bigger and busier than El Valle. There are tall buildings, big malls, and many cars. The busiest place is the Cinta Costera on Sundays.",
                "El Valle is smaller and quieter than the city. It is also cooler, because it is in the mountains. The most famous place in El Valle is the Sunday market. People sell flowers, fruit, and crafts there.",
                "For me, El Valle is more beautiful than the city, but the city is more exciting. Which place do you prefer?"]},
             "qs": [
    {"t": "mc", "q": "Where do Ana's grandparents live?", "opts": ["in Panama City", "in El Valle de Antón", "in the mountains of Chiriquí"], "a": 1,
     "exp": "*My grandparents live in El Valle de Antón.* Ana vive en la ciudad."},
    {"t": "tf", "q": "El Valle is busier than Panama City.", "a": False,
     "exp": "Es al revés: *Panama City is bigger and **busier** than El Valle.* El Valle es más **tranquilo** (*quieter*)."},
    {"t": "short", "q": "Why is El Valle cooler? Because it is in the ______________.",
     "accept": [["mountains", "the mountains", "mountain"]], "show": "**mountains**",
     "exp": "*It is also cooler, because it is in the mountains.*"},
    {"t": "mc", "q": "What is the most famous place in El Valle?", "opts": ["the mall", "the Cinta Costera", "the Sunday market"], "a": 2,
     "exp": "*The most famous place in El Valle is the Sunday market.* La Cinta Costera está en la ciudad."},
    {"t": "short", "q": "For Ana, El Valle is ______________ than the city.",
     "accept": [["more beautiful"]], "show": "**more beautiful**",
     "exp": "*beautiful* es larga: se usa **more** beautiful, nunca *beautifuler*."},
    {"t": "tf", "q": "For Ana, the city is more exciting than El Valle.", "a": True, "exp": "*...but the city is more exciting.*"},
  ]}]},

 "writing": {"skill": "writing", "total": 10,
  "tip": ["Revisa siempre: palabra corta → **-er / the -est**; palabra larga → **more / the most**; y después del comparativo va **than**, no *that*."],
  "review": "Gramática A y B: la tabla de comparativos y los Errores comunes",
  "parts": [
   {"intro": "**Parte A. Cada oración tiene un error. Escríbela correctamente.** (1 punto cada una)", "qs": [
    {"t": "fix", "q": "The market is more busy than the park.", "accept": ["the market is busier than the park"],
     "show": "The market is **busier** than the park.", "exp": "busy termina en y → busier, sin *more*"},
    {"t": "fix", "q": "My school is bigger that your school.", "accept": ["my school is bigger than your school"],
     "show": "My school is bigger **than** your school.", "exp": "en comparaciones se usa *than*"},
    {"t": "fix", "q": "The church is the most old building.", "accept": ["the church is the oldest building"],
     "show": "The church is **the oldest** building.", "exp": "old es corta → the oldest"},
    {"t": "fix", "q": "The park is beautifuler than the market.", "accept": ["the park is more beautiful than the market"],
     "show": "The park is **more beautiful** than the market.", "exp": "beautiful es larga → more beautiful"},
    {"t": "fix", "q": "There is two parks in my community.", "accept": ["there are two parks in my community"],
     "show": "There **are** two parks in my community.", "exp": "varias cosas → there are"},
   ]},
   {"intro": "**Parte B. Responde el mensaje de Tomás** con 3 a 5 oraciones. (5 puntos)",
    "note": ["Mensaje de Tomás", "*Hi! I want to visit your community. What places are there? Which place is the busiest? What is the most beautiful place?*"],
    "open": {"lines": 5, "min_sent": 3, "max_sent": 5, "check_intro": "**Revisa tu respuesta.** Marca un punto por cada casilla que cumpliste:",
             "checklist": [
               {"text": "Empecé con un saludo (*Hi, Tomás!*).", "auto": r"^\s*(hi|hello|hey|dear)\b"},
               {"text": "Usé *There is* o *There are* para nombrar lugares.", "auto": r"\bthere (is|are|'s)\b"},
               {"text": "Escribí un comparativo con *than* (*busier than...*).", "auto": r"\b(\w+er|more \w+) than\b"},
               {"text": "Escribí un superlativo con *the* (*the busiest / the most...*).", "auto": r"\bthe (\w+est|most \w+)\b"},
               {"text": "Cada oración empieza con mayúscula y termina con punto.", "auto": "caps"}],
             "sample": "Hi, Tomás! In my community there is a market, a park, and a church. The market is the busiest place. The park is quieter than the market. The most beautiful place is the river. Come soon!"}},
  ]},

 "speaking": {"skill": "speaking", "total": 8,
  "tip": ["Responde siempre con **oración completa**: no solo *The market*, sino *The market is the busiest place.*",
          "Si no sabes una palabra, no te detengas: di la idea con palabras que sí conoces."],
  "review": "Audio 06: escucha, repite y grábate otra vez",
  "parts": [{"intro": "Prepara una grabadora (o usa la de esta página) y luego reproduce el audio. Escucharás 5 preguntas; responde cada una en voz alta **durante la pausa**.",
             "audio": "07",
             "open": {"record": True, "check_intro": "Después, escucha tu grabación y marca un punto por cada casilla:", "checklist": [
               {"text": "Pregunta 1 con oración completa (*My community is called...*)"},
               {"text": "Pregunta 2: usé *There is / There are*"},
               {"text": "Pregunta 3: usé un superlativo y *because*"},
               {"text": "Pregunta 4: usé un comparativo con *than*"},
               {"text": "Pregunta 5: usé *the most beautiful*"},
               {"text": "Pronuncié *than* y *the* con la lengua entre los dientes"},
               {"text": "Hablé sin leer"}, {"text": "No usé español"}]}}]},

 "mediation": {"skill": "mediation", "total": 8,
  "tip": ["Para simplificar: quédate con **qué, dónde y cuándo**. Borra lo demás y usa oraciones cortas."],
  "review": "El Consejo de Mediation: qué, dónde y cuándo",
  "parts": [
   {"intro": "**Parte A.** Tu vecina dejó esta nota en español. Escríbele a Tomás, que solo habla inglés, un mensaje de **2 o 3 oraciones simples**.",
    "note": ["Nota de la vecina", "El sábado hay feria en el parque. Este año es más grande que el año pasado. Empieza a las nueve de la mañana."],
    "open": {"lines": 3, "min_sent": 2, "max_sent": 3, "checklist": [
      {"text": "Dije que hay una feria (*fair*).", "auto": r"\bfair\b"},
      {"text": "Dije **dónde** (*in the park*).", "auto": r"\bpark\b"},
      {"text": "Dije **cuándo** (*on Saturday, at nine*).", "auto": r"\bsaturday\b"},
      {"text": "Usé un comparativo (*bigger than last year*).", "auto": r"\bbigger\b|\bmore \w+ than\b|\b\w+er than\b"},
      {"text": "Usé oraciones cortas y claras."}],
     "sample": "Hi, Tomás! On Saturday there is a fair in the park. It is bigger than last year. It starts at nine in the morning."}},
   {"intro": "**Parte B.** Simplifica este aviso en **1 o 2 oraciones** para un compañero que está aprendiendo inglés.",
    "note": ["Aviso", "*Because the market is the busiest place in our community on Saturday mornings, all visitors are asked to park their cars next to the church.*"],
    "open": {"lines": 2, "min_sent": 1, "max_sent": 2, "checklist": [
      {"text": "Dije **dónde** estacionar (*next to the church*).", "auto": r"\bchurch\b"},
      {"text": "Dije **cuándo** (*on Saturday*).", "auto": r"\bsaturday\b"},
      {"text": "Dije **por qué** (*the market is busy*).", "auto": r"\bbus(y|iest|ier)\b"}],
     "sample": "On Saturday, the market is very busy. Park your car next to the church."}},
  ]},
}
