# -*- coding: utf-8 -*-
"""Mini-tests del Tema 5.2 (fuente única para el libro y la versión en línea)."""
from common import *

TESTS = {
 "listening": {"skill": "listening", "total": 6,
  "tip": ["Antes de escuchar, **lee todas las preguntas**. Así sabes qué información buscar.",
          "En este tema el audio tiene **muchos números y años**. Escríbelos al margen mientras escuchas: 1976, 4, 100, 14, 500..."],
  "review": "Vocabulario (audio 01), *Cómo se leen los años* y la práctica con el audio 04 en velocidad lenta",
  "parts": [{"intro": "Escucha al director Castillo en el aniversario de su escuela. Puedes escuchar **dos veces como máximo**, como en una prueba real.",
             "audio": "05", "qs": [
    {"t": "mc", "q": "How long has the school been there?", "opts": ["for fifteen years", "for fifty years", "since 2015"], "a": 1,
     "exp": "*Our school has been here for fifty years!* Cuidado: *fifty* (50) y *fifteen* (15) suenan parecido; en *fifty* el acento va al inicio: FIF-ty."},
    {"t": "mc", "q": "When did the school open?", "opts": ["in 1976", "in 1967", "in 2019"], "a": 0,
     "exp": "*It opened in 1976* (nineteen seventy-six)."},
    {"t": "short", "q": "Now the school has ______________ classrooms.",
     "accept": [["14", "fourteen"]], "show": "**fourteen** (14)",
     "exp": "En 1976 había **cuatro** (*four*); ahora hay **catorce** (*fourteen*)."},
    {"t": "tf", "q": "The school has had a new cafeteria since 2015.", "a": True,
     "exp": "*We have had a new cafeteria since 2015.*"},
    {"t": "tf", "q": "The computer room opened in 1976.", "a": False,
     "exp": "La sala de computadoras abrió **el año pasado** (*last year*)."},
    {"t": "mc", "q": "How long has Mr. Castillo been the principal?", "opts": ["since 1976", "for fifty years", "since 2019"], "a": 2,
     "exp": "*I have been the principal since 2019.*"},
  ]}]},

 "reading": {"skill": "reading", "total": 6,
  "tip": ["Lee primero las preguntas y luego el texto. **Subraya** en el texto la parte donde está cada respuesta.",
          "Si la pregunta dice **How long**, busca en el texto **for** o **since**: la respuesta está justo después."],
  "review": "La lectura *Grandpa's School* y la Gramática C y D",
  "parts": [{"intro": "Lee el artículo del periódico escolar y responde.",
             "reading": {"title": "Meet Mr. Pedro, Our Gardener", "paras": [
                "Mr. Pedro has worked at our school since 1998. That is more than twenty-five years! Before that, he was a farmer in Coclé.",
                "He has taken care of the school garden for a long time. The garden has changed a lot. In 1998 there were only two mango trees. Now there are mango, lemon, and orange trees, and a small vegetable garden.",
                "Many students have helped Mr. Pedro. They have planted flowers and vegetables, and they have learned to recycle water.",
                "Mr. Pedro says: \"I have been happy here every day. The students are my second family.\""]},
             "qs": [
    {"t": "short", "q": "Mr. Pedro has worked at the school since ______________.",
     "accept": [["1998"]], "show": "**1998**"},
    {"t": "mc", "q": "What was Mr. Pedro's job before?", "opts": ["a teacher", "a farmer", "a principal"], "a": 1,
     "exp": "*Before that, he was a farmer in Coclé.*"},
    {"t": "tf", "q": "The garden hasn't changed.", "a": False,
     "exp": "*The garden has changed a lot*: antes había 2 árboles de mango; ahora hay más árboles y un huerto."},
    {"t": "mc", "q": "How many trees were there in 1998?", "opts": ["two", "three", "twelve"], "a": 0,
     "exp": "*In 1998 there were only two mango trees.*"},
    {"t": "short", "q": "The students have learned to ______________ water.",
     "accept": [["recycle"]], "show": "**recycle**", "exp": "*...they have learned to recycle water.*"},
    {"t": "tf", "q": "Mr. Pedro thinks the students are like his family.", "a": True,
     "exp": "*The students are my second family.*"},
  ]}]},

 "writing": {"skill": "writing", "total": 10,
  "tip": ["Revisa tres cosas: **has** con he / she / it, el **participio** correcto (been, lived, had...) y **for** (cantidad) o **since** (momento)."],
  "review": "Gramática A, B y C, y los Errores comunes",
  "parts": [
   {"intro": "**Parte A. Cada oración tiene un error. Escríbela correctamente.** (1 punto cada una)", "qs": [
    {"t": "fix", "q": "The school has been here since sixty years.", "accept": ["the school has been here for sixty years", "the school has been here for 60 years"],
     "show": "The school has been here **for** sixty years.", "exp": "sixty years es una cantidad → for"},
    {"t": "fix", "q": "My family have lived here for ten years.", "accept": ["my family has lived here for ten years", "my family has lived here for 10 years"],
     "show": "My family **has** lived here for ten years.", "exp": "my family = it → has"},
    {"t": "fix", "q": "I have been at this school for 2020.", "accept": ["i have been at this school since 2020"],
     "show": "I have been at this school **since** 2020.", "exp": "2020 es un momento → since"},
    {"t": "fix", "q": "How long has the library be open?", "accept": ["how long has the library been open"],
     "show": "How long has the library **been** open?", "exp": "después de has, el participio: been"},
    {"t": "fix", "q": "Has the building change?", "accept": ["has the building changed"],
     "show": "Has the building **changed**?", "exp": "participio de change: changed"},
   ]},
   {"intro": "**Parte B. Responde el mensaje de Carmen** para el periódico escolar con 3 a 5 oraciones. (5 puntos)",
    "note": ["Mensaje de Carmen", "*Hi! I'm writing about our students. How long have you been at this school? How long have you lived in your community? Has your school changed?*"],
    "open": {"lines": 5, "min_sent": 3, "max_sent": 5, "check_intro": "**Revisa tu respuesta.** Marca un punto por cada casilla que cumpliste:",
             "checklist": [
               {"text": "Empecé con un saludo (*Hi, Carmen!*).", "auto": r"^\s*(hi|hello|hey|dear)\b"},
               {"text": "Usé el presente perfecto (*I have been / I have lived*).", "auto": r"\b(have|has|'ve)\s+(been|lived|studied|had|known|changed|worked)\b"},
               {"text": "Usé **for** con una cantidad de tiempo.", "auto": r"\bfor\s+(a|an|one|two|three|four|five|six|seven|eight|nine|ten|eleven|twelve|many|\d+)\b"},
               {"text": "Usé **since** con un momento.", "auto": r"\bsince\b"},
               {"text": "Cada oración empieza con mayúscula y termina con punto.", "auto": "caps"}],
             "sample": "Hi, Carmen! I have been at this school for six years. I have lived in my community since 2014. Yes, my school has changed. We have had a new library since last year."}},
  ]},

 "speaking": {"skill": "speaking", "total": 8,
  "tip": ["Responde siempre con **oración completa**: no solo *Six years*, sino *I have been at this school for six years.*",
          "Si no recuerdas un año exacto, usa **for** con una cantidad aproximada: *for about five years*."],
  "review": "Audio 06: escucha, repite y grábate otra vez",
  "parts": [{"intro": "Prepara una grabadora (o usa la de esta página) y luego reproduce el audio. Escucharás 5 preguntas; responde cada una en voz alta **durante la pausa**.",
             "audio": "07",
             "open": {"record": True, "check_intro": "Después, escucha tu grabación y marca un punto por cada casilla:", "checklist": [
               {"text": "Pregunta 1: *I have been at this school for / since...*"},
               {"text": "Pregunta 2: *I have lived here for / since...*"},
               {"text": "Pregunta 3: *Yes, it has. / No, it hasn't.* y un cambio"},
               {"text": "Pregunta 4: usé *I have known...*"},
               {"text": "Pregunta 5: usé *since*"},
               {"text": "Pronuncié la **h** de *have / has*"},
               {"text": "Hablé sin leer"}, {"text": "No usé español"}]}}]},

 "mediation": {"skill": "mediation", "total": 8,
  "tip": ["Para pasar fechas y tiempos a otro idioma: busca primero **desde cuándo** o **cuánto tiempo**, y decide si va **since** o **for**."],
  "review": "La práctica de Mediation y la Gramática C (for / since)",
  "parts": [
   {"intro": "**Parte A.** Escríbele a Carmen (solo habla inglés) lo que contó tu abuelo, en **2 o 3 oraciones**.",
    "note": ["Lo que dijo el abuelo", "Vivo en esta comunidad desde 1970. Fui estudiante de la escuela por seis años. La escuela tiene biblioteca desde 2012."],
    "open": {"lines": 3, "min_sent": 2, "max_sent": 3, "checklist": [
      {"text": "Dije desde cuándo vive aquí (*since 1970*).", "auto": r"\bsince 1970\b"},
      {"text": "Dije cuánto tiempo fue estudiante (*for six years*).", "auto": r"\bfor (six|6) years\b"},
      {"text": "Mencioné la biblioteca (*library*).", "auto": r"\blibrary\b"},
      {"text": "Usé *has / have* + participio.", "auto": r"\b(has|have|'s|'ve)\s+(been|lived|had)\b"},
      {"text": "Usé oraciones cortas y claras."}],
     "sample": "My grandfather has lived in this community since 1970. He was a student at the school for six years. The school has had a library since 2012."}},
   {"intro": "**Parte B.** Simplifica este aviso en **1 o 2 oraciones**.",
    "note": ["Aviso", "*Since the school has been here for fifty years, all families are invited to a special anniversary celebration in the cafeteria on Friday afternoon.*"],
    "open": {"lines": 2, "min_sent": 1, "max_sent": 2, "checklist": [
      {"text": "Dije **qué** (*a party / celebration*).", "auto": r"\b(party|celebration|anniversary)\b"},
      {"text": "Dije **dónde** (*in the cafeteria*).", "auto": r"\bcafeteria\b"},
      {"text": "Dije **cuándo** (*on Friday*).", "auto": r"\bfriday\b"}],
     "sample": "The school is fifty years old. There is a party in the cafeteria on Friday afternoon."}},
  ]},
}
