# -*- coding: utf-8 -*-
"""Mini-tests del Tema 6.2 (fuente única para el libro y la versión en línea)."""
from common import *

TESTS = {
 "listening": {"skill": "listening", "total": 6,
  "tip": ["Antes de escuchar, **lee todas las preguntas**. Así sabes qué información buscar.",
          "En un pronóstico de la semana, escribe los días al margen (Mon, Tue, Wed...) y anota una palabra junto a cada uno mientras escuchas."],
  "review": "Vocabulario (audio 01), *Los días de la semana* y la práctica con el audio 04 en velocidad lenta",
  "parts": [{"intro": "Escucha a Valeria con el pronóstico de la semana. Puedes escuchar **dos veces como máximo**, como en una prueba real.",
             "audio": "05", "qs": [
    {"t": "mc", "q": "What will the weather be like on Monday?", "opts": ["sunny and hot", "cloudy and cool", "rainy all day"], "a": 0,
     "exp": "*On Monday, it will be sunny and hot, thirty-two degrees.*"},
    {"t": "mc", "q": "When will there be a storm?", "opts": ["Monday afternoon", "Tuesday afternoon", "Friday morning"], "a": 1,
     "exp": "*On Tuesday... there will be a storm in the afternoon.*"},
    {"t": "short", "q": "On Wednesday and Thursday, the temperature will go down to ______________ degrees.",
     "accept": [["23", "twenty-three", "twenty three"]], "show": "**twenty-three** (23)", "exp": "El lunes había 32; el miércoles **baja** (*go down*) a 23."},
    {"t": "mc", "q": "What should you wear on Wednesday?", "opts": ["a hat", "a jacket", "sandals"], "a": 1, "exp": "*You should wear a jacket.*"},
    {"t": "tf", "q": "It will rain on Friday.", "a": False, "exp": "*On Friday, the rain will **stop**, and it will be sunny again.*"},
    {"t": "tf", "q": "It will be windy on the weekend.", "a": True,
     "exp": "*Will it be windy on the weekend? Yes, it will.* Por eso dice que es buen fin de semana para volar papalote (*kite*)."},
  ]}]},

 "reading": {"skill": "reading", "total": 6,
  "tip": ["Lee primero las preguntas y luego el texto. **Subraya** en el texto la parte donde está cada respuesta.",
          "Las preguntas con **Will...?** se responden *Yes, it will.* o *No, it won't.* Busca en el texto si ese día dice el tiempo que te preguntan."],
  "review": "La lectura *Tomorrow's Weather in Coclé* y la Gramática C y D",
  "parts": [{"intro": "Lee el diario del tiempo que escribió Ana para su clase y responde.",
             "reading": {"title": "Ana's Weather Diary", "paras": [
                "**Monday:** This morning the sky was blue and it was hot. Then, at two o'clock, the sky changed. It was cloudy and windy.",
                "**Tuesday:** Now it is 4:00 p.m. Look at the black clouds! It's going to rain. I'm going to close the windows.",
                "**Wednesday:** The forecast says the weather will change tomorrow. First it will be cool and cloudy, then it will be sunny. The temperature will go up to 31 degrees.",
                "**My prediction:** I think it will be sunny on the weekend. We are going to go to the beach!"]},
             "qs": [
    {"t": "mc", "q": "How did the weather change on Monday?", "opts": ["from rainy to sunny", "from sunny and hot to cloudy and windy", "from cold to hot"], "a": 1,
     "exp": "*The sky was blue and it was hot. Then... It was cloudy and windy.*"},
    {"t": "short", "q": "On Tuesday, Ana is going to close the ______________.", "accept": [["windows", "window", "the windows"]], "show": "**windows**",
     "exp": "Ve nubes negras: *It's going to rain. I'm going to close the windows.*"},
    {"t": "tf", "q": "On Tuesday, Ana uses going to because she can see the clouds.", "a": True,
     "exp": "*Look at the black clouds! It's going to rain.* Hay evidencia → **going to**."},
    {"t": "mc", "q": "What will the weather be like first on Thursday?", "opts": ["hot and sunny", "cool and cloudy", "stormy"], "a": 1,
     "exp": "*First it will be cool and cloudy, then it will be sunny.*"},
    {"t": "short", "q": "On Thursday, the temperature will go up to ______________ degrees.", "accept": [["31", "thirty-one", "thirty one"]], "show": "**31**"},
    {"t": "tf", "q": "Ana's family is going to go to the river on the weekend.", "a": False, "exp": "*We are going to go to the **beach**!*"},
  ]}]},

 "writing": {"skill": "writing", "total": 10,
  "tip": ["Revisa: **going to** siempre lleva *am / is / are* antes (*It's going to rain*), y la respuesta corta a *Will...?* es *Yes, it will. / No, it won't.*"],
  "review": "Gramática A, B y C, y los Errores comunes",
  "parts": [
   {"intro": "**Parte A. Cada oración tiene un error. Escríbela correctamente.** (1 punto cada una)", "qs": [
    {"t": "fix", "q": "Look at the clouds! It going to rain.", "accept": ["look at the clouds its going to rain", "look at the clouds it is going to rain"],
     "show": "Look at the clouds! It**'s** going to rain.", "exp": "falta is"},
    {"t": "fix", "q": "Will it rain tomorrow? — Yes, it is.", "accept": ["will it rain tomorrow yes it will"],
     "show": "Will it rain tomorrow? — Yes, it **will**.", "exp": "la respuesta corta repite will"},
    {"t": "fix", "q": "The weather will to change tonight.", "accept": ["the weather will change tonight"],
     "show": "The weather will **change** tonight.", "exp": "después de will, sin to"},
    {"t": "fix", "q": "We is going to play tomorrow.", "accept": ["we are going to play tomorrow", "were going to play tomorrow"],
     "show": "We **are** going to play tomorrow.", "exp": "con we: are"},
    {"t": "fix", "q": "The temperature will go up tonight, so you should wear a jacket.", "accept": ["the temperature will go down tonight so you should wear a jacket"],
     "show": "The temperature will go **down** tonight, so you should wear a jacket.", "exp": "si necesitas chaqueta, la temperatura baja: go down"},
   ]},
   {"intro": "**Parte B. Escríbele a Ana cómo cambiará el tiempo mañana** en tu comunidad, con 3 a 5 oraciones. (5 puntos)",
    "note": ["Mensaje de Ana", "*Hi! We want to have a picnic tomorrow. How will the weather change? Will it rain?*"],
    "open": {"lines": 5, "min_sent": 3, "max_sent": 5, "check_intro": "**Revisa tu respuesta.** Marca un punto por cada casilla que cumpliste:",
             "checklist": [
               {"text": "Usé **will** para el pronóstico.", "auto": r"\bwill\b|'ll\b"},
               {"text": "Conté el cambio con **first / then / later**.", "auto": r"\b(first|then|later)\b"},
               {"text": "Respondí si va a llover (*Yes, it will / No, it won't / it's going to rain*).", "auto": r"\b(it will|it won'?t|will not|going to rain|will rain)\b"},
               {"text": "Di un consejo con **should**.", "auto": r"\bshould\b"},
               {"text": "Cada oración empieza con mayúscula y termina con punto.", "auto": "caps"}],
             "sample": "Hi, Ana! Tomorrow the weather will change. First it will be sunny and hot. Then it will be cloudy, and later it will rain. You should have the picnic in the morning."}},
  ]},

 "speaking": {"skill": "speaking", "total": 8,
  "tip": ["Responde siempre con **oración completa**: no solo *No*, sino *No, it won't. It will be sunny.*",
          "Cuando la pregunta dice **What is going to happen?**, responde con **going to**."],
  "review": "Audio 06: escucha, repite y grábate otra vez",
  "parts": [{"intro": "Prepara una grabadora (o usa la de esta página) y luego reproduce el audio. Escucharás 5 preguntas; responde cada una en voz alta **durante la pausa**.",
             "audio": "07",
             "open": {"record": True, "check_intro": "Después, escucha tu grabación y marca un punto por cada casilla:", "checklist": [
               {"text": "Pregunta 1: *It is... now.*"},
               {"text": "Pregunta 2: usé *first / then* y *will*"},
               {"text": "Pregunta 3: *Yes, it will. / No, it won't.*"},
               {"text": "Pregunta 4: usé *It's going to...*"},
               {"text": "Pregunta 5: usé *should*"},
               {"text": "Pronuncié la **r** de *rain* sin tocar el paladar"},
               {"text": "Hablé sin leer"}, {"text": "No usé español"}]}}]},

 "mediation": {"skill": "mediation", "total": 8,
  "tip": ["Para explicar un cambio del tiempo, usa **palabras de orden** (*first, then, later*) y palabras clave. Un dibujo con flechas también ayuda."],
  "review": "La práctica de Mediation y la Gramática D (first, then, later)",
  "parts": [
   {"intro": "**Parte A.** Escríbele a Ana (solo habla inglés) lo que dijo tu papá, en **2 o 3 oraciones**.",
    "note": ["Lo que dijo tu papá", "Mañana primero va a estar nublado y después va a llover toda la tarde. En la noche va a hacer frío."],
    "open": {"lines": 3, "min_sent": 2, "max_sent": 3, "checklist": [
      {"text": "Dije **mañana** (*tomorrow*).", "auto": r"\btomorrow\b"},
      {"text": "Usé **first** y **then** (o *later*).", "auto": r"\bfirst\b.*\b(then|later)\b"},
      {"text": "Dije que estará nublado y que lloverá.", "auto": r"\bcloudy\b.*\brain|\brain.*\bcloudy\b"},
      {"text": "Dije que hará frío en la noche.", "auto": r"\bcold\b"},
      {"text": "Usé oraciones cortas y claras."}],
     "sample": "Tomorrow, first it will be cloudy, then it will rain all afternoon. At night, it will be cold."}},
   {"intro": "**Parte B.** Simplifica este aviso en **1 o 2 oraciones**.",
    "note": ["Aviso", "*Because heavy rain is expected on Thursday afternoon, the school field trip to the beach has been moved to Friday morning.*"],
    "open": {"lines": 2, "min_sent": 1, "max_sent": 2, "checklist": [
      {"text": "Dije que va a llover el jueves.", "auto": r"\bthursday\b"},
      {"text": "Mencioné el paseo a la playa (*trip / beach*).", "auto": r"\b(trip|beach)\b"},
      {"text": "Dije el nuevo día (*on Friday*).", "auto": r"\bfriday\b"}],
     "sample": "It is going to rain on Thursday. The beach trip will be on Friday morning."}},
  ]},
}
